language: cpp

sudo: required

matrix:

  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - libstdc++-8-dev
            - clang-6.0
            - cmake
            - libgtest-dev
      env: 
        MATRIX_EVAL="
          CC=clang-6.0 && 
          CXX=clang++-6.0 && 
          CXXSTD=-std=c++17 && 
          CXXSTDLIB=-stdlib=libstdc++ && 
          COV='llvm-cov gcov'"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libgtest-dev
      env:
        MATRIX_EVAL="
          CC=gcc-7 && 
          CXX=g++-7 && 
          CXXSTD=-std=c++17 && 
          CXXSTDLIB= && 
          COV=gcov-7"


before_install:
  # Compiler Env
  - |
    echo $MATRIX_EVAL
    eval $MATRIX_EVAL
  - |
    $CC --version
    $CXX --version
  # Codecov
  - sudo pip install codecov

script:
  - |
    mkdir build/cmake
    cd build/cmake
    # Generate makefile
    cmake -D ENABLE_CODECOV=1 ../..
    # Build
    make
    # Test
    make test

after_success: 
  # Send report
  - bash <(curl -s https://codecov.io/bash) -x $COV
