language: cpp

sudo: required

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - g++-7
      - clang-6.0
      - cmake
      - libgtest-dev
env:
  - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" CC=clang-6.0 CXX=clang++-6.0

before_install:
  # Codecov
  - sudo pip install codecov
  # Google Test
  - cd /usr/src/gtest
  - sudo cmake -E make_directory build
  - sudo cmake -E chdir build cmake .. >> /dev/null
  - sudo cmake --build build >> /dev/null
  - sudo cp build/libgtest* /usr/local/lib/
  - sudo rm -rf build
  # Return
  - cd "${TRAVIS_BUILD_DIR}"

install:
  # Gcov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90

script:
  # Compile Test
  - cd test
  - clang++-6.0 -fprofile-arcs -ftest-coverage -std=c++2a -stdlib=libstdc++ -I ../src/ -lpthread -lgtest_main -lgtest parser-test.cpp -o parser-test
  # Run Test
  - ./parser-test
  # Run Codecov
  - gcov-7 -n -o ./test ./test/parser-test.cpp > /dev/null
  - codecov

after_success: 
  # Send report
  - bash <(curl -s https://codecov.io/bash) -t a2cd89ab-e481-43e8-b24d-df2f437569a4
