language: cpp

sudo: required

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - g++-7
      - clang-6.0
      - cmake
      - libgtest-dev
env:
  matrix:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" CC=clang-6.0 CXX=clang++-6.0 COV="llvm-cov gcov"
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" CC=gcc-7 CXX=g++-7 COV=gcov-7

before_install:
  # Codecov
  - sudo pip install codecov
  # Google Test
  - cd /usr/src/gtest
  - sudo cmake -E make_directory build
  - sudo cmake -E chdir build cmake .. >> /dev/null
  - sudo cmake --build build >> /dev/null
  - sudo cp build/libgtest* /usr/local/lib/
  - sudo rm -rf build
  # Return
  - cd "${TRAVIS_BUILD_DIR}"

install:
  # Gcov
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90

script:
  # Compile Test
  - cd test
  - $CXX -std=c++2a -stdlib=libstdc++ -lpthread -fprofile-arcs -ftest-coverage  -I ../src/ -lgtest_main -lgtest parser-test.cpp -o parser-test
  # Run Test
  - ./parser-test
  # Run Codecov
  - $COV -n -o . parser-test.cpp > /dev/null

after_success: 
  # Send report
  - bash <(curl -s https://codecov.io/bash) -t a2cd89ab-e481-43e8-b24d-df2f437569a4 -x $COV
