language: cpp

sudo: required

matrix:

  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - libstdc++-8-dev
            - clang-7.0
            - libgtest-dev
            - lcov
      env: 
        MATRIX_EVAL="
          CC=clang-6.0 && 
          CXX=clang++-6.0 && 
          CXXSTD=-std=c++17 && 
          CXXSTDLIB=-stdlib=libstdc++ && 
          COV='llvm-cov gcov'"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgtest-dev
            - lcov
      env:
        MATRIX_EVAL="
          CC=gcc-7 && 
          CXX=g++-7 && 
          CXXSTD=-std=c++17 && 
          CXXSTDLIB= && 
          COV=gcov-7"


before_install:
  # Compiler Env
  - |
    echo $MATRIX_EVAL
    eval $MATRIX_EVAL
  - |
    $CC --version
    $CXX --version
  # Codecov
  - sudo pip install codecov
  # CMake
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
      CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi


script:
  - |
    mkdir build/cmake
    cd build/cmake
  # Generate makefile
  - cmake -D ENABLE_CODECOV=ON ../..
  # Build
  - make
  # Test
  - make test

after_success: 
  # Send report
  - |
    cd build/cmake
    bash <(curl -s https://codecov.io/bash) -x $COV
