language: cpp

sudo: required

matrix:

  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - libstdc++-8-dev
            - clang-6.0
            - cmake
            - libgtest-dev
      env: 
        MATRIX_EVAL="
          CC=clang-6.0 && 
          CXX=clang++-6.0 && 
          CXXSTD=-std=c++17 && 
          CXXSTDLIB=-stdlib=libstdc++ && 
          COV='llvm-cov gcov'"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libgtest-dev
      env:
        MATRIX_EVAL="
          CC=gcc-7 && 
          CXX=g++-7 && 
          CXXSTD=-std=c++17 && 
          CXXSTDLIB= && 
          COV=gcov-7"


before_install:
  # Compiler Env
  - |
    echo $MATRIX_EVAL
    eval $MATRIX_EVAL
  - |
    $CC --version
    $CXX --version
  # Codecov
  - sudo pip install codecov
  # Google Test
  - |
    # Enter dir
    cd /usr/src/gtest
    # Build
    sudo cmake -E make_directory build
    sudo cmake -E chdir build cmake .. >> /dev/null
    sudo cmake --build build >> /dev/null
    # Copy libs
    sudo cp build/libgtest* /usr/local/lib/
    sudo rm -rf build
    # Return
    cd "${TRAVIS_BUILD_DIR}"

script:
  # Compile Test
  - |
    cd test
    $CXX $CXXSTD $CXXSTDLIB -pthread -fprofile-arcs -ftest-coverage  -I ../src/ -lgtest_main -lgtest parser-test.cpp -o parser-test
  # Run Test
  - ./parser-test

after_success: 
  # Run Codecov
  - $COV -n -o . parser-test.cpp > /dev/null
  # Send report
  - bash <(curl -s https://codecov.io/bash) -t a2cd89ab-e481-43e8-b24d-df2f437569a4 -x $COV
