language: cpp

sudo: required

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - cmake
      - libgtest-dev
env:
  - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
  - CC=clang-6.0
  - CMAKE_C_COMPILER=clang-6.0
  - CXX=clang++-6.0
  - CMAKE_CXX_COMPILER=clang++-6.0

before_install:
- cd /usr/src/gtest
- sudo cmake -E make_directory build
- sudo cmake -E chdir build cmake .. >> /dev/null
- sudo cmake --build build >> /dev/null
- sudo cp build/libgtest* /usr/local/lib/
- sudo rm -rf build
- cd "${TRAVIS_BUILD_DIR}"

script:
- clang++ -std=c++2a -I ./src/ -l gtest_main -l gtest ./test/parser-test.cpp -o parser-test
- ./parser-test
