image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:
  - cd build/msvc2017/chtholly
  - nuget restore

test_script:
  - dir
  - "%configuration%\\test_parser"
  - "%configuration%\\test_irgen"
