image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:
  - cd build/msvc2017/chtholly
  - nuget restore

test_script:
  - Debug\test_parser
  - Debug\test_irgen
