image: Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

install:
  - cd build/msvc2017/chtholly
  - nuget restore

test_script:
  - dir
  - "%platform%\\%configuration%\\test_parser"
  - "%platform%\\%configuration%\\test_irgen"
