image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:
  - cd build/msvc2017/chtholly
  - nuget restore

test_script:
  - IF "%platform%"=="x86" (SET platform=Win32)
  - "%platform%\\%configuration%\\test_parser"
  - "%platform%\\%configuration%\\test_irgen"
