version: 2.1

executors:
  clang:
    docker:
      - image: buildpack-deps:disco-scm
        command:
          - apt-get update -yqq && apt-get install -yqq clang-8
    environment:
      C:    clang-8
      CXX:  clang++-8
      COV:  'llvm-cov gcov'
  gcc:
    docker:
      - image: buildpack-deps:disco-scm
        command:
          - apt-get update -yqq && apt-get install -yqq g++-9
    environment:
      C:    gcc-9
      CXX:  g++-9
      COV:  gcov

commands:
  install-cmake:
    steps:
      - run: apt-get update -yqq && apt-get install -yqq cmake
  build-and-test:
    steps:
      - run: mkdir build/cmake
      # Generate makefile
      - run: cd build/cmake && cmake -D ENABLE_CODECOV=ON ../..
      # Build
      - run: cd build/cmake && make
      # Test
      - run: cd build/cmake && make test

jobs:
  build-with-clang:
    executor: clang
    steps:
      - checkout
      - install-cmake
      - build-and-test
  build-with-gcc:
    executor: gcc
    steps:
      - checkout
      - install-cmake
      - build-and-test

workflows:
  version: 2
  build-with-clang:
    jobs:
      - build-with-clang
  build-with-gcc:
    jobs:
      - build-with-gcc
