version: 2.1

commands:
  install-deps:
    steps:
      - run: apt-get update -yqq && apt-get install -yqq cmake lcov libgtest
  install-clang:
      - run: apt-get update -yqq && apt-get install -yqq clang-8
      - run: C=clang-8 && CXX=clang++-8 && COV='llvm-cov gcov'
  install-gcc:
      - run: apt-get update -yqq && apt-get install -yqq g++-9
      - run: C=gcc-9 && CXX=g++-9 && COV=gcov
  build-and-test:
    steps:
      - run: mkdir build/cmake
      # Generate makefile
      - run: cd build/cmake && cmake -D ENABLE_CODECOV=ON ../..
      # Build
      - run: cd build/cmake && make
      # Test
      - run: cd build/cmake && make test

jobs:
  build-with-clang:
    docker: 
      - image: buildpack-deps:disco-scm
    steps:
      - checkout
      - install-clang
      - install-deps
      - build-and-test
  build-with-gcc:
    docker: 
      - image: buildpack-deps:disco-scm
    steps:
      - checkout
      - install-gcc
      - install-deps
      - build-and-test

workflows:
  version: 2
  build-with-clang:
    jobs:
      - build-with-clang
  build-with-gcc:
    jobs:
      - build-with-gcc
