version: 2.1

executors:
  clang:
    docker:
      - image: teeks99/clang-ubuntu:8
    environment:
      C:    clang-8
      CXX:  clang++-8
      COV:  'llvm-cov gcov'
  gcc:
    docker:
      - image: buildpack-deps:bionic-scm
      - image: gcc:8
    environment:
      C:    gcc-8
      CXX:  g++-8
      COV:  gcov

commands:
  install-cmake:
    steps:
      - run: apt-get install -y cmake
  build-and-test:
    steps:
      - run: |
          mkdir build/cmake
          cd build/cmake
      # Generate makefile
      - run: cmake -D ENABLE_CODECOV=ON ../..
      # Build
      - run: make
      # Test
      - run: make test


jobs:
  build-with-clang:
    executor: clang
    steps:
      - checkout
      - install-cmake
      - build-and-test
  build-with-gcc:
    executor: gcc
    steps:
      - checkout
      - install-cmake
      - build-and-test

workflows:
  version: 2
  build-with-clang:
    jobs:
      - build-with-clang
  build-with-gcc:
    jobs:
      - build-with-gcc
